from .adversarial_pretrain import AdversarialPretrainer, AdversarialPretrainerConfig, DistributedAdversarialPretrainer, AdversarialBertWrapper
from .translator_train import TranslatorTrainer, TranslatorTrainerConfig
